import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const altform = localFont({
  src: [
    {
      path: '../assets/fonts/altform/Altform-Light.otf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../assets/fonts/altform/Altform-LightItalic.otf',
      weight: '300',
      style: 'italic',
    },
    {
      path: '../assets/fonts/altform/Altform-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../assets/fonts/altform/Altform-RegularItalic.otf',
      weight: '400',
      style: 'italic',
    },
    {
      path: '../assets/fonts/altform/Altform-Bold.otf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../assets/fonts/altform/Altform-BoldItalic.otf',
      weight: '700',
      style: 'italic',
    },
  ],
  variable: "--font-altform",
})

const editorial = localFont({
  src: [
    {
      path: '../assets/fonts/editorial/EditorialNew-Ultralight.otf',
      weight: '200',
      style: 'normal',
    },
    {
      path: '../assets/fonts/editorial/EditorialNew-UltralightItalic.otf',
      weight: '200',
      style: 'italic',
    },
    {
      path: '../assets/fonts/editorial/EditorialNew-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../assets/fonts/editorial/EditorialNew-Italic.otf',
      weight: '400',
      style: 'italic',
    },
    {
      path: '../assets/fonts/editorial/EditorialNew-Ultrabold.otf',
      weight: '800',
      style: 'normal',
    },
    {
      path: '../assets/fonts/editorial/EditorialNew-UltraboldItalic.otf',
      weight: '800',
      style: 'italic',
    },
  ],
  variable: "--font-editorial",
})

// const capriola = Capriola({
//   subsets: ["latin"],
//   weight: "400",
//   variable: "--font-capriola",
// });

export const metadata: Metadata = {
  title: "Panda Pay",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${altform.variable} ${editorial.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
